name: Linting

on: [push]

jobs:
  styles:
    runs-on: ubuntu-18.04
    name: Linting
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.3.0
        with:
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
