name: Publish to PyPI and TestPyPI

on: push

jobs:
  pypi:
    name: Publish to PyPI and TestPyPI
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: __token__
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install pre-requisites and build source distribution
        run: |
          pip3 install twine wheel
          make
      - name: Publish to TestPyPI
        if: startsWith(github.ref, 'refs/tags/test-v')
        env:
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: make testpypi
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: make pypi