name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test_requirements.txt
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Check formatting
      run: |
        yapf --diff --recursive --verbose linkbudget/
    - name: Test with pytest
      run: |
        pytest
  pypi:
    name: Publish to PyPI and TestPyPI
    needs: test
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: __token__
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install pre-requisites and build source distribution
        run: |
          pip3 install twine wheel
          make
      - name: Publish to TestPyPI
        if: startsWith(github.ref, 'refs/tags/test-v')
        env:
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: make testpypi
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: make pypi
